-- 011_geography_locations.sql
-- Référentiel géographique pays / régions / villes pour Agri-Control.
-- Granularité : 1 ligne = 1 ville rattachée à un pays et une région.
-- Source logique : régions officielles Maroc + communautés autonomes Espagne ; liste de villes opérationnelle initiale, extensible par INSERT.

CREATE TABLE IF NOT EXISTS geography_locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country_id TEXT NOT NULL,
  country_code TEXT NOT NULL,
  country_name TEXT NOT NULL,
  region_id TEXT NOT NULL,
  region_code TEXT NOT NULL,
  region_name TEXT NOT NULL,
  city_id TEXT NOT NULL,
  city_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT geography_locations_country_code_check CHECK (country_code IN ('MA', 'ES')),
  CONSTRAINT geography_locations_unique_city UNIQUE (country_id, region_id, city_id)
);

CREATE INDEX IF NOT EXISTS idx_geography_locations_country ON geography_locations(country_id);
CREATE INDEX IF NOT EXISTS idx_geography_locations_region ON geography_locations(country_id, region_id);
CREATE INDEX IF NOT EXISTS idx_geography_locations_city ON geography_locations(city_name);

INSERT INTO geography_locations (country_id, country_code, country_name, region_id, region_code, region_name, city_id, city_name) VALUES
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_tanger', 'Tanger'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_tetouan', 'Tétouan'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_larache', 'Larache'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_ksar_el_kebir', 'Ksar El Kébir'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_al_hoceima', 'Al Hoceïma'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_chefchaouen', 'Chefchaouen'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_fnideq', 'Fnideq'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_mdiq', 'Mdiq'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ttah', 'MA_TTAH', 'Tanger-Tétouan-Al Hoceïma', 'city_ma_ouazzane', 'Ouazzane'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_oujda', 'Oujda'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_berkane', 'Berkane'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_nador', 'Nador'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_driouch', 'Driouch'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_figuig', 'Figuig'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_taourirt', 'Taourirt'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_guercif', 'Guercif'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_jerada', 'Jerada'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_ahfir', 'Ahfir'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ori', 'MA_ORI', 'L''Oriental', 'city_ma_saidia', 'Saidia'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_fes', 'Fès'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_meknes', 'Meknès'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_ifrane', 'Ifrane'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_sefrou', 'Séfrou'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_taza', 'Taza'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_taounate', 'Taounate'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_el_hajeb', 'El Hajeb'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_moulay_yacoub', 'Moulay Yacoub'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_boulemane', 'Boulemane'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_fm', 'MA_FM', 'Fès-Meknès', 'city_ma_missour', 'Missour'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_rabat', 'Rabat'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_sale', 'Salé'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_kenitra', 'Kénitra'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_skhirate_temara', 'Skhirate-Témara'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_sidi_kacem', 'Sidi Kacem'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_sidi_slimane', 'Sidi Slimane'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_khemisset', 'Khémisset'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_tiflet', 'Tiflet'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_rsk', 'MA_RSK', 'Rabat-Salé-Kénitra', 'city_ma_mehdia', 'Mehdia'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_bmk', 'MA_BMK', 'Béni Mellal-Khénifra', 'city_ma_beni_mellal', 'Béni Mellal'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_bmk', 'MA_BMK', 'Béni Mellal-Khénifra', 'city_ma_khenifra', 'Khénifra'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_bmk', 'MA_BMK', 'Béni Mellal-Khénifra', 'city_ma_fquih_ben_salah', 'Fquih Ben Salah'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_bmk', 'MA_BMK', 'Béni Mellal-Khénifra', 'city_ma_azilal', 'Azilal'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_bmk', 'MA_BMK', 'Béni Mellal-Khénifra', 'city_ma_khouribga', 'Khouribga'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_bmk', 'MA_BMK', 'Béni Mellal-Khénifra', 'city_ma_oued_zem', 'Oued Zem'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_bmk', 'MA_BMK', 'Béni Mellal-Khénifra', 'city_ma_kasba_tadla', 'Kasba Tadla'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_casablanca', 'Casablanca'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_settat', 'Settat'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_berrechid', 'Berrechid'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_el_jadida', 'El Jadida'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_mohammedia', 'Mohammedia'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_nouaceur', 'Nouaceur'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_mediouna', 'Médiouna'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_sidi_bennour', 'Sidi Bennour'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_benslimane', 'Benslimane'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_azemmour', 'Azemmour'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_cs', 'MA_CS', 'Casablanca-Settat', 'city_ma_bouznika', 'Bouznika'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_marrakech', 'Marrakech'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_safi', 'Safi'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_essaouira', 'Essaouira'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_chichaoua', 'Chichaoua'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_el_kelaa_des_sraghna', 'El Kelâa des Sraghna'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_rehamna', 'Rehamna'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_youssoufia', 'Youssoufia'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_ben_guerir', 'Ben Guerir'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_ms', 'MA_MS', 'Marrakech-Safi', 'city_ma_sidi_bou_othmane', 'Sidi Bou Othmane'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dt', 'MA_DT', 'Drâa-Tafilalet', 'city_ma_errachidia', 'Errachidia'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dt', 'MA_DT', 'Drâa-Tafilalet', 'city_ma_ouarzazate', 'Ouarzazate'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dt', 'MA_DT', 'Drâa-Tafilalet', 'city_ma_zagora', 'Zagora'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dt', 'MA_DT', 'Drâa-Tafilalet', 'city_ma_midelt', 'Midelt'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dt', 'MA_DT', 'Drâa-Tafilalet', 'city_ma_tinghir', 'Tinghir'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dt', 'MA_DT', 'Drâa-Tafilalet', 'city_ma_rissani', 'Rissani'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dt', 'MA_DT', 'Drâa-Tafilalet', 'city_ma_arfoud', 'Arfoud'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dt', 'MA_DT', 'Drâa-Tafilalet', 'city_ma_kalaat_mgouna', 'Kalaat M’Gouna'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_agadir', 'Agadir'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_inezgane', 'Inezgane'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_ait_melloul', 'Aït Melloul'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_taroudant', 'Taroudant'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_tiznit', 'Tiznit'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_chtouka_ait_baha', 'Chtouka-Aït Baha'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_biougra', 'Biougra'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_ouled_teima', 'Ouled Teima'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_tata', 'Tata'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_sm', 'MA_SM', 'Souss-Massa', 'city_ma_aoulouz', 'Aoulouz'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_gon', 'MA_GON', 'Guelmim-Oued Noun', 'city_ma_guelmim', 'Guelmim'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_gon', 'MA_GON', 'Guelmim-Oued Noun', 'city_ma_tan_tan', 'Tan-Tan'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_gon', 'MA_GON', 'Guelmim-Oued Noun', 'city_ma_sidi_ifni', 'Sidi Ifni'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_gon', 'MA_GON', 'Guelmim-Oued Noun', 'city_ma_assa_zag', 'Assa-Zag'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_gon', 'MA_GON', 'Guelmim-Oued Noun', 'city_ma_bouizakarne', 'Bouizakarne'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_lsh', 'MA_LSH', 'Laâyoune-Sakia El Hamra', 'city_ma_laayoune', 'Laâyoune'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_lsh', 'MA_LSH', 'Laâyoune-Sakia El Hamra', 'city_ma_boujdour', 'Boujdour'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_lsh', 'MA_LSH', 'Laâyoune-Sakia El Hamra', 'city_ma_tarfaya', 'Tarfaya'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_lsh', 'MA_LSH', 'Laâyoune-Sakia El Hamra', 'city_ma_es_semara', 'Es-Semara'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dod', 'MA_DOD', 'Dakhla-Oued Ed-Dahab', 'city_ma_dakhla', 'Dakhla'),
  ('country_ma', 'MA', 'Maroc', 'region_ma_dod', 'MA_DOD', 'Dakhla-Oued Ed-Dahab', 'city_ma_aousserd', 'Aousserd'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_almeria', 'Almería'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_cadix', 'Cadix'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_cordoue', 'Cordoue'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_grenade', 'Grenade'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_huelva', 'Huelva'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_jaen', 'Jaén'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_malaga', 'Málaga'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_seville', 'Séville'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_jerez_de_la_frontera', 'Jerez de la Frontera'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_marbella', 'Marbella'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_el_ejido', 'El Ejido'),
  ('country_es', 'ES', 'Espagne', 'region_es_an', 'ES_AN', 'Andalousie', 'city_es_roquetas_de_mar', 'Roquetas de Mar'),
  ('country_es', 'ES', 'Espagne', 'region_es_ar', 'ES_AR', 'Aragon', 'city_es_saragosse', 'Saragosse'),
  ('country_es', 'ES', 'Espagne', 'region_es_ar', 'ES_AR', 'Aragon', 'city_es_huesca', 'Huesca'),
  ('country_es', 'ES', 'Espagne', 'region_es_ar', 'ES_AR', 'Aragon', 'city_es_teruel', 'Teruel'),
  ('country_es', 'ES', 'Espagne', 'region_es_ar', 'ES_AR', 'Aragon', 'city_es_calatayud', 'Calatayud'),
  ('country_es', 'ES', 'Espagne', 'region_es_ar', 'ES_AR', 'Aragon', 'city_es_barbastro', 'Barbastro'),
  ('country_es', 'ES', 'Espagne', 'region_es_ar', 'ES_AR', 'Aragon', 'city_es_ejea_de_los_caballeros', 'Ejea de los Caballeros'),
  ('country_es', 'ES', 'Espagne', 'region_es_as', 'ES_AS', 'Asturies', 'city_es_oviedo', 'Oviedo'),
  ('country_es', 'ES', 'Espagne', 'region_es_as', 'ES_AS', 'Asturies', 'city_es_gijon', 'Gijón'),
  ('country_es', 'ES', 'Espagne', 'region_es_as', 'ES_AS', 'Asturies', 'city_es_aviles', 'Avilés'),
  ('country_es', 'ES', 'Espagne', 'region_es_as', 'ES_AS', 'Asturies', 'city_es_langreo', 'Langreo'),
  ('country_es', 'ES', 'Espagne', 'region_es_as', 'ES_AS', 'Asturies', 'city_es_mieres', 'Mieres'),
  ('country_es', 'ES', 'Espagne', 'region_es_ib', 'ES_IB', 'Îles Baléares', 'city_es_palma', 'Palma'),
  ('country_es', 'ES', 'Espagne', 'region_es_ib', 'ES_IB', 'Îles Baléares', 'city_es_ibiza', 'Ibiza'),
  ('country_es', 'ES', 'Espagne', 'region_es_ib', 'ES_IB', 'Îles Baléares', 'city_es_mahon', 'Mahón'),
  ('country_es', 'ES', 'Espagne', 'region_es_ib', 'ES_IB', 'Îles Baléares', 'city_es_manacor', 'Manacor'),
  ('country_es', 'ES', 'Espagne', 'region_es_ib', 'ES_IB', 'Îles Baléares', 'city_es_inca', 'Inca'),
  ('country_es', 'ES', 'Espagne', 'region_es_ib', 'ES_IB', 'Îles Baléares', 'city_es_calvia', 'Calvià'),
  ('country_es', 'ES', 'Espagne', 'region_es_cn', 'ES_CN', 'Îles Canaries', 'city_es_las_palmas_de_gran_canaria', 'Las Palmas de Gran Canaria'),
  ('country_es', 'ES', 'Espagne', 'region_es_cn', 'ES_CN', 'Îles Canaries', 'city_es_santa_cruz_de_tenerife', 'Santa Cruz de Tenerife'),
  ('country_es', 'ES', 'Espagne', 'region_es_cn', 'ES_CN', 'Îles Canaries', 'city_es_san_cristobal_de_la_laguna', 'San Cristóbal de La Laguna'),
  ('country_es', 'ES', 'Espagne', 'region_es_cn', 'ES_CN', 'Îles Canaries', 'city_es_telde', 'Telde'),
  ('country_es', 'ES', 'Espagne', 'region_es_cn', 'ES_CN', 'Îles Canaries', 'city_es_arrecife', 'Arrecife'),
  ('country_es', 'ES', 'Espagne', 'region_es_cn', 'ES_CN', 'Îles Canaries', 'city_es_puerto_del_rosario', 'Puerto del Rosario'),
  ('country_es', 'ES', 'Espagne', 'region_es_cb', 'ES_CB', 'Cantabrie', 'city_es_santander', 'Santander'),
  ('country_es', 'ES', 'Espagne', 'region_es_cb', 'ES_CB', 'Cantabrie', 'city_es_torrelavega', 'Torrelavega'),
  ('country_es', 'ES', 'Espagne', 'region_es_cb', 'ES_CB', 'Cantabrie', 'city_es_castro_urdiales', 'Castro-Urdiales'),
  ('country_es', 'ES', 'Espagne', 'region_es_cm', 'ES_CM', 'Castille-La Manche', 'city_es_albacete', 'Albacete'),
  ('country_es', 'ES', 'Espagne', 'region_es_cm', 'ES_CM', 'Castille-La Manche', 'city_es_ciudad_real', 'Ciudad Real'),
  ('country_es', 'ES', 'Espagne', 'region_es_cm', 'ES_CM', 'Castille-La Manche', 'city_es_cuenca', 'Cuenca'),
  ('country_es', 'ES', 'Espagne', 'region_es_cm', 'ES_CM', 'Castille-La Manche', 'city_es_guadalajara', 'Guadalajara'),
  ('country_es', 'ES', 'Espagne', 'region_es_cm', 'ES_CM', 'Castille-La Manche', 'city_es_tolede', 'Tolède'),
  ('country_es', 'ES', 'Espagne', 'region_es_cm', 'ES_CM', 'Castille-La Manche', 'city_es_talavera_de_la_reina', 'Talavera de la Reina'),
  ('country_es', 'ES', 'Espagne', 'region_es_cm', 'ES_CM', 'Castille-La Manche', 'city_es_puertollano', 'Puertollano'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_avila', 'Ávila'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_burgos', 'Burgos'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_leon', 'León'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_palencia', 'Palencia'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_salamanque', 'Salamanque'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_segovie', 'Ségovie'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_soria', 'Soria'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_valladolid', 'Valladolid'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_zamora', 'Zamora'),
  ('country_es', 'ES', 'Espagne', 'region_es_cl', 'ES_CL', 'Castille-et-León', 'city_es_ponferrada', 'Ponferrada'),
  ('country_es', 'ES', 'Espagne', 'region_es_ct', 'ES_CT', 'Catalogne', 'city_es_barcelone', 'Barcelone'),
  ('country_es', 'ES', 'Espagne', 'region_es_ct', 'ES_CT', 'Catalogne', 'city_es_gerone', 'Gérone'),
  ('country_es', 'ES', 'Espagne', 'region_es_ct', 'ES_CT', 'Catalogne', 'city_es_lleida', 'Lleida'),
  ('country_es', 'ES', 'Espagne', 'region_es_ct', 'ES_CT', 'Catalogne', 'city_es_tarragone', 'Tarragone'),
  ('country_es', 'ES', 'Espagne', 'region_es_ct', 'ES_CT', 'Catalogne', 'city_es_hospitalet_de_llobregat', 'Hospitalet de Llobregat'),
  ('country_es', 'ES', 'Espagne', 'region_es_ct', 'ES_CT', 'Catalogne', 'city_es_badalona', 'Badalona'),
  ('country_es', 'ES', 'Espagne', 'region_es_ct', 'ES_CT', 'Catalogne', 'city_es_terrassa', 'Terrassa'),
  ('country_es', 'ES', 'Espagne', 'region_es_ct', 'ES_CT', 'Catalogne', 'city_es_sabadell', 'Sabadell'),
  ('country_es', 'ES', 'Espagne', 'region_es_vc', 'ES_VC', 'Communauté valencienne', 'city_es_valence', 'Valence'),
  ('country_es', 'ES', 'Espagne', 'region_es_vc', 'ES_VC', 'Communauté valencienne', 'city_es_alicante', 'Alicante'),
  ('country_es', 'ES', 'Espagne', 'region_es_vc', 'ES_VC', 'Communauté valencienne', 'city_es_castellon_de_la_plana', 'Castellón de la Plana'),
  ('country_es', 'ES', 'Espagne', 'region_es_vc', 'ES_VC', 'Communauté valencienne', 'city_es_elche', 'Elche'),
  ('country_es', 'ES', 'Espagne', 'region_es_vc', 'ES_VC', 'Communauté valencienne', 'city_es_torrevieja', 'Torrevieja'),
  ('country_es', 'ES', 'Espagne', 'region_es_vc', 'ES_VC', 'Communauté valencienne', 'city_es_orihuela', 'Orihuela'),
  ('country_es', 'ES', 'Espagne', 'region_es_vc', 'ES_VC', 'Communauté valencienne', 'city_es_gandia', 'Gandia'),
  ('country_es', 'ES', 'Espagne', 'region_es_ex', 'ES_EX', 'Estrémadure', 'city_es_badajoz', 'Badajoz'),
  ('country_es', 'ES', 'Espagne', 'region_es_ex', 'ES_EX', 'Estrémadure', 'city_es_caceres', 'Cáceres'),
  ('country_es', 'ES', 'Espagne', 'region_es_ex', 'ES_EX', 'Estrémadure', 'city_es_merida', 'Mérida'),
  ('country_es', 'ES', 'Espagne', 'region_es_ex', 'ES_EX', 'Estrémadure', 'city_es_plasencia', 'Plasencia'),
  ('country_es', 'ES', 'Espagne', 'region_es_ex', 'ES_EX', 'Estrémadure', 'city_es_don_benito', 'Don Benito'),
  ('country_es', 'ES', 'Espagne', 'region_es_ga', 'ES_GA', 'Galice', 'city_es_la_corogne', 'La Corogne'),
  ('country_es', 'ES', 'Espagne', 'region_es_ga', 'ES_GA', 'Galice', 'city_es_lugo', 'Lugo'),
  ('country_es', 'ES', 'Espagne', 'region_es_ga', 'ES_GA', 'Galice', 'city_es_ourense', 'Ourense'),
  ('country_es', 'ES', 'Espagne', 'region_es_ga', 'ES_GA', 'Galice', 'city_es_pontevedra', 'Pontevedra'),
  ('country_es', 'ES', 'Espagne', 'region_es_ga', 'ES_GA', 'Galice', 'city_es_vigo', 'Vigo'),
  ('country_es', 'ES', 'Espagne', 'region_es_ga', 'ES_GA', 'Galice', 'city_es_saint_jacques_de_compostelle', 'Saint-Jacques-de-Compostelle'),
  ('country_es', 'ES', 'Espagne', 'region_es_ga', 'ES_GA', 'Galice', 'city_es_ferrol', 'Ferrol'),
  ('country_es', 'ES', 'Espagne', 'region_es_md', 'ES_MD', 'Madrid', 'city_es_madrid', 'Madrid'),
  ('country_es', 'ES', 'Espagne', 'region_es_md', 'ES_MD', 'Madrid', 'city_es_alcala_de_henares', 'Alcalá de Henares'),
  ('country_es', 'ES', 'Espagne', 'region_es_md', 'ES_MD', 'Madrid', 'city_es_getafe', 'Getafe'),
  ('country_es', 'ES', 'Espagne', 'region_es_md', 'ES_MD', 'Madrid', 'city_es_leganes', 'Leganés'),
  ('country_es', 'ES', 'Espagne', 'region_es_md', 'ES_MD', 'Madrid', 'city_es_mostoles', 'Móstoles'),
  ('country_es', 'ES', 'Espagne', 'region_es_md', 'ES_MD', 'Madrid', 'city_es_alcorcon', 'Alcorcón'),
  ('country_es', 'ES', 'Espagne', 'region_es_md', 'ES_MD', 'Madrid', 'city_es_fuenlabrada', 'Fuenlabrada'),
  ('country_es', 'ES', 'Espagne', 'region_es_mc', 'ES_MC', 'Murcie', 'city_es_murcie', 'Murcie'),
  ('country_es', 'ES', 'Espagne', 'region_es_mc', 'ES_MC', 'Murcie', 'city_es_carthagene', 'Carthagène'),
  ('country_es', 'ES', 'Espagne', 'region_es_mc', 'ES_MC', 'Murcie', 'city_es_lorca', 'Lorca'),
  ('country_es', 'ES', 'Espagne', 'region_es_mc', 'ES_MC', 'Murcie', 'city_es_molina_de_segura', 'Molina de Segura'),
  ('country_es', 'ES', 'Espagne', 'region_es_mc', 'ES_MC', 'Murcie', 'city_es_alcantarilla', 'Alcantarilla'),
  ('country_es', 'ES', 'Espagne', 'region_es_nc', 'ES_NC', 'Navarre', 'city_es_pampelune', 'Pampelune'),
  ('country_es', 'ES', 'Espagne', 'region_es_nc', 'ES_NC', 'Navarre', 'city_es_tudela', 'Tudela'),
  ('country_es', 'ES', 'Espagne', 'region_es_nc', 'ES_NC', 'Navarre', 'city_es_estella_lizarra', 'Estella-Lizarra'),
  ('country_es', 'ES', 'Espagne', 'region_es_nc', 'ES_NC', 'Navarre', 'city_es_baranain', 'Barañáin'),
  ('country_es', 'ES', 'Espagne', 'region_es_pv', 'ES_PV', 'Pays basque', 'city_es_bilbao', 'Bilbao'),
  ('country_es', 'ES', 'Espagne', 'region_es_pv', 'ES_PV', 'Pays basque', 'city_es_saint_sebastien', 'Saint-Sébastien'),
  ('country_es', 'ES', 'Espagne', 'region_es_pv', 'ES_PV', 'Pays basque', 'city_es_vitoria_gasteiz', 'Vitoria-Gasteiz'),
  ('country_es', 'ES', 'Espagne', 'region_es_pv', 'ES_PV', 'Pays basque', 'city_es_barakaldo', 'Barakaldo'),
  ('country_es', 'ES', 'Espagne', 'region_es_pv', 'ES_PV', 'Pays basque', 'city_es_getxo', 'Getxo'),
  ('country_es', 'ES', 'Espagne', 'region_es_pv', 'ES_PV', 'Pays basque', 'city_es_irun', 'Irun'),
  ('country_es', 'ES', 'Espagne', 'region_es_ri', 'ES_RI', 'La Rioja', 'city_es_logrono', 'Logroño'),
  ('country_es', 'ES', 'Espagne', 'region_es_ri', 'ES_RI', 'La Rioja', 'city_es_calahorra', 'Calahorra'),
  ('country_es', 'ES', 'Espagne', 'region_es_ri', 'ES_RI', 'La Rioja', 'city_es_arnedo', 'Arnedo'),
  ('country_es', 'ES', 'Espagne', 'region_es_ri', 'ES_RI', 'La Rioja', 'city_es_haro', 'Haro'),
  ('country_es', 'ES', 'Espagne', 'region_es_ce', 'ES_CE', 'Ceuta', 'city_es_ceuta', 'Ceuta'),
  ('country_es', 'ES', 'Espagne', 'region_es_ml', 'ES_ML', 'Melilla', 'city_es_melilla', 'Melilla')
ON CONFLICT (country_id, region_id, city_id) DO UPDATE SET
  country_code = EXCLUDED.country_code,
  country_name = EXCLUDED.country_name,
  region_code = EXCLUDED.region_code,
  region_name = EXCLUDED.region_name,
  city_name = EXCLUDED.city_name,
  is_active = TRUE,
  updated_at = NOW();